#!/usr/bin/env python3
"""
Generate platform/pc/src/pc_string_table.c -- a startup fixup for gStringTable.

gStringTable[100] (0x8010102c) is defined in src/text.c via
`#include "assets/8010102c.inc"`, whose entries are ABSOLUTE PSX ADDRESSES
(e.g. `(u8 *)0x800154bc` -> "Valley of Thieves"). Those addresses point into
text.c's byte-exact placeholder blobs (D_800151C8[888] and the D_80122FBx[8]
arrays). On real hardware the pointers are correct because the data sits at
exactly those addresses; on the PC port the same data is relocated to ordinary
host addresses, so every gStringTable entry is a dangling pointer and any UI
that draws from it (world-map destination names via world_map.c's
gStringTable[33]/[34], and every "#N" string-table escape in DrawText/
DrawSjisText) rendered blank.

Rather than gate the byte-exact text.c definition, we fix it up at runtime:
this file embeds the real string contents (dereferenced from the byte-exact
SLUS_004.47) and a constructor rewrites each gStringTable[i] to point at the
embedded copy. Static-initialized data is ready before any constructor runs, so
the rewrite is safe; the handful of runtime self-copies the game does
(gStringTable[0]/[32] = gStringTable[x]) just copy the already-fixed pointers.
NULL entries (88..99), plus the PC port's added sentinel entry 100, are normalized to a stable empty
string. This matches the zero read produced by the Linux i386 fault fixup without relying on
architecture-specific fault decoding, and makes every in-range table lookup safe on all PC targets.

Stage-2 PC-port backend file only; the matching build never sees it.
"""
import os
import re
import struct

HERE = os.path.dirname(os.path.abspath(__file__))
VH = os.path.abspath(os.path.join(HERE, "..", "..", ".."))   # tools -> pc -> platform -> vh
SLUS = os.environ.get("VH_PSX_EXE", os.path.join(VH, "SLUS_004.47"))
OUT = os.environ.get("VH_GENERATED_OUT",
                     os.path.join(VH, "platform", "pc", "src", "pc_string_table.c"))

COUNT = 100
TABLE_ADDR = 0x8010102c
LOAD_ADDR = 0x80010000
FILE_BASE = 0x800


def foff(addr):
    return addr - LOAD_ADDR + FILE_BASE


def c_escape(s):
    out = []
    for ch in s:
        o = ord(ch)
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif ch == "\r":
            out.append("\\r")
        elif 0x20 <= o < 0x7f:
            out.append(ch)
        else:
            out.append('\\x%02x" "' % o)
    return "".join(out)


def main():
    data = open(SLUS, "rb").read()
    ptrs = struct.unpack_from("<%dI" % COUNT, data, foff(TABLE_ADDR))

    strings = []
    for p in ptrs:
        if p == 0:
            strings.append(None)
        else:
            o = foff(p)
            e = data.index(b"\0", o)
            strings.append(data[o:e].decode("latin1"))

    lines = []
    lines.append("/* GENERATED by platform/pc/tools/gen_string_table.py -- do not edit by hand. */")
    lines.append("/* Runtime fixup for gStringTable (0x8010102c): the byte-exact text.c initializer")
    lines.append(" * holds absolute PSX addresses that dangle on the PC port. We rewrite each entry")
    lines.append(" * to the embedded string below at startup. See the generator header. */")
    lines.append("")
    lines.append("extern unsigned char *gStringTable[101];")
    lines.append("static unsigned char s_pc_empty_string[] = \"\";")
    lines.append("")
    lines.append("static const char *const s_pc_strings[%d] = {" % COUNT)
    for i, s in enumerate(strings):
        if s is None:
            lines.append("    0, /* [%d] */" % i)
        else:
            lines.append('    "%s", /* [%d] */' % (c_escape(s), i))
    lines.append("};")
    lines.append("")
    lines.append("__attribute__((constructor))")
    lines.append("static void PC_FixupStringTable(void) {")
    lines.append("    int i;")
    lines.append("    for (i = 0; i < %d; i++) {" % COUNT)
    lines.append("        gStringTable[i] = s_pc_strings[i]")
    lines.append("            ? (unsigned char *)s_pc_strings[i] : s_pc_empty_string;")
    lines.append("    }")
    lines.append("    gStringTable[%d] = s_pc_empty_string; /* PC sentinel used transiently by dojo.c */" % COUNT)
    lines.append("}")
    lines.append("")
    open(OUT, "w").write("\n".join(lines))
    nn = sum(1 for s in strings if s is None)
    print("wrote %s (%d strings, %d NULL)" % (OUT, COUNT - nn, nn))


if __name__ == "__main__":
    main()
