#!/usr/bin/env python3
"""
Generate platform/pc/src/pc_spell_descriptions.c -- a reconstruction of the
`gSpellDescriptions[72]` pointer table (0x800ee9f8 in SLUS_004.47).

`gSpellDescriptions` is an array of 72 `s8*` pointers to the spell/item info
strings ("Healing Magic  Rng:0  Fld:0  MP:2", ...) shown in the bottom window of
the battle spell/item list (drawn by window.c's DrawText_Internal). Because it
is a pointer-containing global, build_data_segment.py can't relocate its bytes
and zero-fills it (see that file's header) -- so on the PC port every entry was
NULL and DrawText_Internal drew nothing, leaving the description window blank.

We recover the real strings straight from the byte-exact binary (each pointer
dereferenced to its NUL-terminated string) and emit them as a normal C array,
then add 'gSpellDescriptions' to build_data_segment.py's MANUALLY_DEFINED so the
generator skips its zeroed stub and the linker uses this definition instead.
This is a stage-2 PC-port backend file only; the matching build never sees it.
"""
import os
import struct

HERE = os.path.dirname(os.path.abspath(__file__))
# tools -> pc -> platform -> vh
VH = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
SLUS = os.environ.get("VH_PSX_EXE", os.path.join(VH, "SLUS_004.47"))
OUT = os.path.join(VH, "platform", "pc", "src", "pc_spell_descriptions.c")

TABLE_ADDR = 0x800ee9f8
COUNT = 72
LOAD_ADDR = 0x80010000
FILE_BASE = 0x800  # SLUS header size; file_off = addr - LOAD_ADDR + FILE_BASE


def foff(addr):
    return addr - LOAD_ADDR + FILE_BASE


def main():
    data = open(SLUS, "rb").read()
    ptrs = struct.unpack("<%dI" % COUNT, data[foff(TABLE_ADDR):foff(TABLE_ADDR) + COUNT * 4])
    strings = []
    for p in ptrs:
        if p == 0:
            strings.append(None)
            continue
        o = foff(p)
        e = data.index(b"\0", o)
        strings.append(data[o:e].decode("latin1"))

    def c_escape(s):
        out = []
        for ch in s:
            if ch == "\\":
                out.append("\\\\")
            elif ch == '"':
                out.append('\\"')
            elif 0x20 <= ord(ch) < 0x7f:
                out.append(ch)
            else:
                out.append("\\x%02x" % ord(ch))
        return "".join(out)

    lines = []
    lines.append("/* GENERATED by platform/pc/tools/gen_spell_descriptions.py -- do not edit by hand. */")
    lines.append("/* Reconstruction of gSpellDescriptions[72] (0x800ee9f8); the data-gen zero-fills")
    lines.append(" * this pointer table, which blanked the battle spell/item info window. See the")
    lines.append(" * generator header. Strings are verbatim from the byte-exact SLUS_004.47. */")
    lines.append("")
    lines.append("char *gSpellDescriptions[%d] = {" % COUNT)
    for i, s in enumerate(strings):
        if s is None:
            lines.append('    0, /* [%d] (was NULL in ROM) */' % i)
        else:
            lines.append('    "%s", /* [%d] */' % (c_escape(s), i))
    lines.append("};")
    lines.append("")
    open(OUT, "w").write("\n".join(lines))
    print("wrote %s (%d entries)" % (OUT, COUNT))


if __name__ == "__main__":
    main()
