#!/usr/bin/env python3
"""Generate AppleClang compatibility declarations for old-style decompiled C."""
import glob
import os
import re
import sys


def main():
    src_dir, output = sys.argv[1:3]
    declarations = {}
    for path in glob.glob(os.path.join(src_dir, "*.c")):
        with open(path, encoding="utf-8", errors="replace") as source:
            text = source.read()
        for match in re.finditer(r"(?m)^void\s+([A-Za-z_]\w*)\s*\(", text):
            depth = 0
            close = None
            for pos in range(match.end() - 1, len(text)):
                if text[pos] == "(":
                    depth += 1
                elif text[pos] == ")":
                    depth -= 1
                    if depth == 0:
                        close = pos
                        break
            if close is None or text[close + 1:].lstrip()[:1] != "{":
                continue
            name = match.group(1)
            if name == "main" or not re.search(r"\b%s\s*\(" % re.escape(name), text[:match.start()]):
                continue
            signature = " ".join(text[match.start():close + 1].split())
            stem = re.sub(r"\W", "_", os.path.splitext(os.path.basename(path))[0])
            declarations.setdefault(stem, {})[name] = signature
    lines = ["/* Generated by gen_apple_forward_decls.py; do not edit. */",
             "#ifndef VH_APPLE_VOID_FORWARD_DECLS_H", "#define VH_APPLE_VOID_FORWARD_DECLS_H"]
    for stem in sorted(declarations):
        lines.append("#if defined(VH_APPLE_TU_%s)" % stem)
        for name in sorted(declarations[stem]):
            lines.append(declarations[stem][name] + ";")
        lines.append("#endif")
    lines.append("#endif")
    content = "\n".join(lines) + "\n"
    try:
        if open(output).read() == content:
            return
    except OSError:
        pass
    with open(output, "w") as header:
        header.write(content)


if __name__ == "__main__":
    main()
