#!/usr/bin/env python3
"""
Generate platform/pc/src/pc_item_descriptions.c -- reconstructions of the
`gItemDescriptions[101]` (0x800ef3d8) and `gItemDescriptions2[101]` (0x800ef56c)
pointer tables.

Both are arrays of 101 `s8*` pointers to item/equipment info strings
("LIGHT SWORD  AT+4", "Restores some HP  Rng:1  Fld:0", ...). gItemDescriptions
is the single-line form drawn in the party/overworld item window (window.c:2078,
DrawText_Internal); gItemDescriptions2 is the shop form with an embedded '\n'
(supplies.c, DrawText). Being pointer-containing globals, build_data_segment.py
can't relocate their bytes and zero-fills them (see that file's header), so on
the PC port every entry was NULL and the description window rendered blank.

Same fix pattern as gen_spell_descriptions.py: dereference each pointer in the
byte-exact binary to its string and emit real C arrays, then add both symbols to
build_data_segment.py's MANUALLY_DEFINED so its zeroed stubs are skipped.

NOTE: gTextPointers (0x8012be9c) is a *runtime-filled* table -- all-NULL in the
ROM image (.bss), populated by the game at load time -- so it is correctly left
zeroed by the data-gen and is NOT reconstructed here.

Stage-2 PC-port backend file only; the matching build never sees it.
"""
import os
import struct

HERE = os.path.dirname(os.path.abspath(__file__))
VH = os.path.abspath(os.path.join(HERE, "..", "..", ".."))   # tools -> pc -> platform -> vh
SLUS = os.environ.get("VH_PSX_EXE", os.path.join(VH, "SLUS_004.47"))
OUT = os.environ.get("VH_GENERATED_OUT",
                     os.path.join(VH, "platform", "pc", "src", "pc_item_descriptions.c"))

LOAD_ADDR = 0x80010000
FILE_BASE = 0x800

TABLES = [
    ("gItemDescriptions",  0x800ef3d8, 101),
    ("gItemDescriptions2", 0x800ef56c, 101),
]


def foff(addr):
    return addr - LOAD_ADDR + FILE_BASE


def c_escape(s):
    out = []
    for ch in s:
        o = ord(ch)
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif ch == "\r":
            out.append("\\r")
        elif 0x20 <= o < 0x7f:
            out.append(ch)
        else:
            # close+reopen so a following hex/octal digit can't extend the escape
            out.append('\\x%02x" "' % o)
    return "".join(out)


def main():
    data = open(SLUS, "rb").read()
    lines = []
    lines.append("/* GENERATED by platform/pc/tools/gen_item_descriptions.py -- do not edit by hand. */")
    lines.append("/* Reconstruction of the gItemDescriptions/gItemDescriptions2 pointer tables that")
    lines.append(" * the data-gen zero-fills, which blanked the item/equipment description window.")
    lines.append(" * Strings are verbatim from the byte-exact SLUS_004.47. See the generator header. */")
    lines.append("")
    for name, addr, count in TABLES:
        ptrs = struct.unpack("<%dI" % count, data[foff(addr):foff(addr) + count * 4])
        lines.append("char *%s[%d] = {" % (name, count))
        for i, p in enumerate(ptrs):
            if p == 0:
                lines.append("    0, /* [%d] (was NULL in ROM) */" % i)
            else:
                o = foff(p)
                e = data.index(b"\0", o)
                s = data[o:e].decode("latin1")
                lines.append('    "%s", /* [%d] */' % (c_escape(s), i))
        lines.append("};")
        lines.append("")
    open(OUT, "w").write("\n".join(lines))
    print("wrote %s (%s)" % (OUT, ", ".join(n for n, _, _ in TABLES)))


if __name__ == "__main__":
    main()
