#!/usr/bin/env python3
"""
Generate platform/pc/src/pc_kanji_font.c -- the glyph bitmaps that the game's
DrawSjisGlyph() (src/text.c) fetches through Krom2RawAdd().

On real PS1 hardware Krom2RawAdd (BIOS call B(51h)) returns a pointer into the
BIOS ROM kanji character sets at 0xBFC64000 (psx-spx kernelbios.md). Charset 2
(16x15 pixels, "various alphabets, english, greek") holds the full-width
Shift-JIS glyphs Vandal Hearts draws for TURN counters, PLAYER/ENEMY TURN
banners, item names (gItemNamesSjis), gold amounts, party lists, etc. The US
release relies on this ROM font being present -- our PC backend has no BIOS, so
Krom2RawAdd used to return -1 and every DrawSjisText() call rendered nothing
(the ASCII DrawText() path uses the game's own sFontGlyphBitmaps and was
unaffected, which is why only *some* windows were blank).

The PsyQ SDK ships the very same charset data as a redistributable file,
psy-q/3.6/PSYQ/BIN/KROMDAT.BIN, whose layout is byte-identical to the BIOS ROM
region starting at charset 2 (verified: KROMDAT[0x30..] == scph1001.bin
[0x66030..]). Each glyph is 30 bytes (2 bytes/row * 15 rows, 1bpp, MSB=left).

The BIOS packs charset 2 as a *compacted* Shift-JIS sequence (undefined codes
skipped), so the SJIS->glyph-index map is not linear. The indices below were
recovered empirically by rendering KROMDAT glyphs and matching them to
reference bitmaps (see the conversation that produced this file):

    0x8140 (fullwidth space)   -> idx 0    (all-zero glyph)
    0x8144 (fullwidth period)  -> idx 4
    0x824F..0x8258 ('0'..'9')  -> idx 147..156
    0x8260..0x8279 ('A'..'Z')  -> idx 157..182
    0x8281..0x829A ('a'..'z')  -> idx 183..208

That covers every SJIS code Vandal Hearts actually draws (audited against
gItemNamesSjis and every DrawSjisText call site). We embed glyph indices
0..208 inclusive; the SJIS->index mapping itself lives in libkernel.c's
Krom2RawAdd. This is a stage-2 PC-port backend file only -- the matching build
never sees it.
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
# tools -> pc -> platform -> vh -> vandalHearts_decomp
ROOT = os.path.abspath(os.path.join(HERE, "..", "..", "..", ".."))
KROMDAT = os.path.join(ROOT, "psy-q", "3.6", "PSYQ", "BIN", "KROMDAT.BIN")
OUT = os.path.join(ROOT, "vh", "platform", "pc", "src", "pc_kanji_font.c")

GLYPH_BYTES = 30
NUM_GLYPHS = 209          # indices 0..208 (through lowercase 'z')

def main():
    with open(KROMDAT, "rb") as f:
        krom = f.read()
    n = NUM_GLYPHS * GLYPH_BYTES
    if len(krom) < n:
        raise SystemExit(f"KROMDAT.BIN too small: {len(krom)} < {n}")
    blob = krom[:n]

    lines = []
    lines.append("/* GENERATED by platform/pc/tools/gen_kanji_font.py -- do not edit by hand. */")
    lines.append("/* PS1 BIOS kanji charset 2 glyphs (16x15 1bpp, 30 bytes each), glyph")
    lines.append(" * indices 0..208, sourced from PsyQ KROMDAT.BIN. Fetched by Krom2RawAdd")
    lines.append(" * (libkernel.c) for the game's DrawSjisGlyph(). See the generator header. */")
    lines.append("")
    lines.append(f"const unsigned char pc_kanji_charset2[{n}] = {{")
    for i in range(0, n, 15):
        chunk = blob[i:i + 15]
        lines.append("    " + "".join(f"0x{b:02x}," for b in chunk))
    lines.append("};")
    lines.append("")
    with open(OUT, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {OUT} ({n} bytes, {NUM_GLYPHS} glyphs)")

if __name__ == "__main__":
    main()
