#!/usr/bin/env python3
"""
Generate platform/pc/src/pc_kanji_font.c -- the glyph bitmaps that the game's
DrawSjisGlyph() (src/core/text.c) fetches through Krom2RawAdd().

On real PS1 hardware Krom2RawAdd (BIOS call B(51h)) returns a pointer into the
BIOS ROM kanji character sets at 0xBFC64000 (psx-spx kernelbios.md). Charset 2
(16x15 pixels, "various alphabets, english, greek") holds the full-width
Shift-JIS glyphs Vandal Hearts draws for TURN counters, PLAYER/ENEMY TURN
banners, item names (gItemNamesSjis), gold amounts, party lists, etc. The US
release relies on this ROM font being present -- our PC backend has no BIOS, so
Krom2RawAdd used to return -1 and every DrawSjisText() call rendered nothing
(the ASCII DrawText() path uses the game's own sFontGlyphBitmaps and was
unaffected, which is why only *some* windows were blank).

The PsyQ SDK ships the very same charset data as a redistributable file,
psy-q/3.6/PSYQ/BIN/KROMDAT.BIN, whose layout is byte-identical to the BIOS ROM
region starting at charset 2 (verified: KROMDAT[0x30..] == scph1001.bin
[0x66030..]). Each glyph is 30 bytes (2 bytes/row * 15 rows, 1bpp, MSB=left).

The BIOS packs charset 2 as a *compacted* Shift-JIS sequence (undefined codes
skipped), so the SJIS->glyph-index map is not linear. The indices below were
recovered empirically by rendering KROMDAT glyphs and matching them to
reference bitmaps (see the conversation that produced this file):

    0x8140 (fullwidth space)   -> idx 0    (all-zero glyph)
    0x8144 (fullwidth period)  -> idx 4
    0x824F..0x8258 ('0'..'9')  -> idx 147..156
    0x8260..0x8279 ('A'..'Z')  -> idx 157..182
    0x8281..0x829A ('a'..'z')  -> idx 183..208

That covers every SJIS code Vandal Hearts actually draws (audited against
gItemNamesSjis and every DrawSjisText call site). We embed glyph indices
0..208 inclusive; the SJIS->index mapping itself lives in libkernel.c's
Krom2RawAdd. This is a stage-2 PC-port backend file only -- the matching build
never sees it.
"""
import hashlib
import os

HERE = os.path.dirname(os.path.abspath(__file__))
PC_DIR = os.path.abspath(os.path.join(HERE, ".."))
PROJECT_ROOT = os.path.abspath(os.path.join(PC_DIR, "..", ".."))
KROMDAT = os.environ.get("VH_KROM_SOURCE",
                         os.path.join(PROJECT_ROOT, "external", "psy-q", "3.6", "PSYQ", "BIN", "KROMDAT.BIN"))
OUT = os.environ.get("VH_GENERATED_OUT", os.path.join(PC_DIR, "src", "pc_kanji_font.c"))

GLYPH_BYTES = 30
# Region switch (exchange/102 P3): the US game draws only alphanumerics/punctuation through
# Krom2RawAdd, so the US build keeps its audited 209-glyph subset (unchanged output). The JP
# game draws its ENTIRE text repertoire through the BIOS font, so the JP build embeds the whole
# ROM region KROMDAT carries: charset 2 (524 glyphs -- SJIS rows 0x81-0x84: punctuation, digits,
# latin, kana, greek, cyrillic, box drawing) + charset 3 (2965 glyphs -- all JIS level-1 kanji,
# SJIS 0x889F..0x9872), contiguous exactly as in the BIOS at 0xBFC66000 (psx-spx kernelbios.md
# "BIOS Character Sets"). 524*30 + 2965*30 = 104670 = KROMDAT.BIN's size (bar one stray byte),
# which is itself the proof KROMDAT is precisely charsets 2+3. Level-2 kanji are NOT in the ROM:
# Krom2RawAdd returns -1 and the game's own gCustomGlyphs fallback runs, as on hardware.
REGION = os.environ.get("VH_REGION", "us")
NUM_GLYPHS = {"us": 209, "jp": 524 + 2965}[REGION]   # us: 0..208 (through lowercase 'z')
# The generated region is invariant across the supported KROMDAT/Japanese BIOS inputs. Checking
# the exact generated region prevents an arbitrary 512 KiB file (or a wrong-region BIOS) from
# silently producing plausible-sized but corrupt glyph data.
CHARSET2_SHA256 = {
    "us": "19b1dd839020e62a8a0f6dfc673c320da36105d9bc9bbce876aa151b7bd927a7",
    "jp": "014313b691fa9caf95239400653ff61ca90fae8d481e79fa8fc571c7cdf13a86",
}[REGION]

def main():
    with open(KROMDAT, "rb") as f:
        krom = f.read()
    # KROMDAT is byte-identical to the BIOS font region. Accepting a full user-owned BIOS avoids a
    # second proprietary SDK input; charset 2 begins at ROM offset 0x66000.
    if len(krom) == 512 * 1024:
        krom = krom[0x66000:]
    n = NUM_GLYPHS * GLYPH_BYTES
    if len(krom) < n:
        raise SystemExit(f"KROMDAT.BIN too small: {len(krom)} < {n}")
    blob = krom[:n]
    digest = hashlib.sha256(blob).hexdigest()
    if digest != CHARSET2_SHA256:
        raise SystemExit(
            f"unsupported or invalid KROM/BIOS charset-2 data: sha256 {digest} "
            f"(expected {CHARSET2_SHA256})"
        )

    lines = []
    lines.append("/* GENERATED by platform/pc/tools/gen_kanji_font.py -- do not edit by hand. */")
    lines.append("/* PS1 BIOS kanji ROM glyphs (16x15 1bpp, 30 bytes each), %d glyphs" % NUM_GLYPHS)
    lines.append(" * (%s region), sourced from PsyQ KROMDAT.BIN. Fetched by Krom2RawAdd" % REGION)
    lines.append(" * (libkernel.c) for the game's DrawSjisGlyph(). See the generator header. */")
    lines.append("")
    lines.append(f"const unsigned char pc_kanji_charset2[{n}] = {{")
    for i in range(0, n, 15):
        chunk = blob[i:i + 15]
        lines.append("    " + "".join(f"0x{b:02x}," for b in chunk))
    lines.append("};")
    lines.append("")
    with open(OUT, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {OUT} ({n} bytes, {NUM_GLYPHS} glyphs)")

if __name__ == "__main__":
    main()
