/* GENERATED by platform/pc/tools/gen_item_descriptions.py -- do not edit by hand. */
/* Reconstruction of the gItemDescriptions/gItemDescriptions2 pointer tables that
 * the data-gen zero-fills, which blanked the item/equipment description window.
 * Strings are verbatim from the byte-exact SLUS_004.47. See the generator header. */

char *gItemDescriptions[101] = {
    " ", /* [0] */
    "Restores some HP   Rng:1  Fld:0", /* [1] */
    "Restores many HP  Rng:1  Fld:0", /* [2] */
    "Restores 4 MP  Rng:1  Fld:0", /* [3] */
    "Restores 10 MP  Rng:1  Fld:0", /* [4] */
    "Cures Status  Rng:1  Fld:0", /* [5] */
    "Restores party's HP  Rng:<  Fld:<", /* [6] */
    "Restores all HP,MP  Rng:1  Fld:0", /* [7] */
    "Attack magic item  Rng:3  Fld:1", /* [8] */
    "Attack magic item  Rng:0  Fld:2", /* [9] */
    "Attack magic item  Rng:5  Fld:3", /* [10] */
    "Attack magic item  Rng:0  Fld:8", /* [11] */
    "Short sword  AT+2", /* [12] */
    "Light sword  AT+4", /* [13] */
    "Iron sword  AT+10", /* [14] */
    "Greatsword  AT+18", /* [15] */
    "Mastersword  AT+26", /* [16] */
    "Legendary sword  AT+28", /* [17] */
    "Vandal Heart  Soul Blade  AT+40", /* [18] */
    "Hunter bow  AT+2", /* [19] */
    "Light bow  AT+3", /* [20] */
    "Iron bow  AT+8", /* [21] */
    "Steel bow  AT+15", /* [22] */
    "Killer bow  AT+17", /* [23] */
    "Great bow  AT+22", /* [24] */
    "Rune bow  AT+25", /* [25] */
    "Wooden staff  AT+1", /* [26] */
    "Light staff  AT+2", /* [27] */
    "Iron staff  AT+5", /* [28] */
    "Magic staff  AT+9", /* [29] */
    "Spirit staff  AT+10", /* [30] */
    "Arkstaff  AT+13", /* [31] */
    "Runewand  AT+14", /* [32] */
    "Iron axe  AT+12", /* [33] */
    "Battleax  AT+22", /* [34] */
    "", /* [35] */
    "Great axe  AT+27", /* [36] */
    "Ragnarok  AT+39", /* [37] */
    "Iron spear  AT+5", /* [38] */
    "Steel lance  AT+9", /* [39] */
    "Halberd  AT+13", /* [40] */
    "Dragon spear  AT+14", /* [41] */
    "Iron claws  AT+9", /* [42] */
    "Steel claws  AT+17", /* [43] */
    "Panzer claws  AT+20", /* [44] */
    "Death claws  AT+24", /* [45] */
    "Leather helm  DF+2", /* [46] */
    "Light helm  DF+3", /* [47] */
    "Iron helm  DF+7", /* [48] */
    "Steel mask  DF+12", /* [49] */
    "Skull helm  DF+15", /* [50] */
    "Dragon helm  DF+18", /* [51] */
    "Bandanna  DF+1  ", /* [52] */
    "Leather band  DF+2", /* [53] */
    "Iron cap  DF+5", /* [54] */
    "Steel band  DF+9", /* [55] */
    "Leather mask  DF+11", /* [56] */
    "Rune crown  DF+13", /* [57] */
    "Leather armor  DF+4", /* [58] */
    "Padded leather armor  DF+7", /* [59] */
    "Chain mail  DF+17", /* [60] */
    "Scale armor  DF+26", /* [61] */
    "Plate armor  AT+32", /* [62] */
    "Kevlar armor  DF+39", /* [63] */
    "Heavy cape  DF+2", /* [64] */
    "Wool robe  DF+4", /* [65] */
    "Master's robe  DF+10", /* [66] */
    "Mystic robe  DF+18", /* [67] */
    "Zen robe  DF+20", /* [68] */
    "Mojo robe  DF+26", /* [69] */
    "Holy key  Only Ash can use it...", /* [70] */
    "Holy key  Only Ash can use it...", /* [71] */
    "Holy key  Only Ash can use it...", /* [72] */
    "Holy key  Only Ash can use it...", /* [73] */
    "Holy key  Only Ash can use it...", /* [74] */
    "Holy key  Only Ash can use it...", /* [75] */
    "Magicalal and mysterious crystal", /* [76] */
    "Magicalal and mysterious crystal", /* [77] */
    "Magicalal and mysterious crystal", /* [78] */
    "Magicalal and mysterious crystal", /* [79] */
    "Magicalal and mysterious crystal", /* [80] */
    "Necessary for Ash's advancement", /* [81] */
    "Vandal helm", /* [82] */
    "Vandal armor", /* [83] */
    "Reforged Vandal Heart ", /* [84] */
    "Rare and expensive antique coins", /* [85] */
    "Precious metal used in alchemy", /* [86] */
    "Golden Axe  AT+0", /* [87] */
    "??????????", /* [88] */
    "??????????", /* [89] */
    "??????????", /* [90] */
    "??????????", /* [91] */
    "??????????", /* [92] */
    "??????????", /* [93] */
    "??????????", /* [94] */
    "??????????", /* [95] */
    "??????????", /* [96] */
    "Smelly green banana", /* [97] */
    "One of 3 collector's treasures", /* [98] */
    "One of 3 collector's treasures", /* [99] */
    "One of 3 collector's treasures", /* [100] */
};

char *gItemDescriptions2[101] = {
    " ", /* [0] */
    "Restores some HP  \nRng:1  Fld:0", /* [1] */
    "Restores many HP  \nRng:1  Fld:0", /* [2] */
    "Restores 4 MP  \nRng:1  Fld:0", /* [3] */
    "Restores 10 MP  \nRng:1  Fld:0", /* [4] */
    "Cures Status  \nRng:1  Fld:0", /* [5] */
    "Restores party's HP  \nRng:<  Fld:<", /* [6] */
    "Restores all HP,MP  \nRng:1  Fld:0", /* [7] */
    "Attack magic item  \nRng:3  Fld:1", /* [8] */
    "Attack magic item  \nRng:0  Fld:2", /* [9] */
    "Attack magic item  \nRng:5  Fld:3", /* [10] */
    "Attack magic item  \nRng:0  Fld:8", /* [11] */
    "Short sword  AT+2", /* [12] */
    "Light sword  AT+4", /* [13] */
    "Iron sword  AT+10", /* [14] */
    "Greatsword  AT+18", /* [15] */
    "Mastersword  AT+26", /* [16] */
    "Legendary sword  AT+28", /* [17] */
    "Vandal Heart  Soul Blade  \nAT+40", /* [18] */
    "Hunter bow  AT+2", /* [19] */
    "Light bow  AT+3", /* [20] */
    "Iron bow  AT+8", /* [21] */
    "Steel bow  AT+15", /* [22] */
    "Killer bow  AT+17", /* [23] */
    "Great bow  AT+22", /* [24] */
    "Rune bow  AT+25", /* [25] */
    "Wooden staff  AT+1", /* [26] */
    "Light staff  AT+2", /* [27] */
    "Iron staff  AT+5", /* [28] */
    "Magic staff  AT+9", /* [29] */
    "Spirit staff  AT+10", /* [30] */
    "Arkstaff  AT+13", /* [31] */
    "Runewand  AT+14", /* [32] */
    "Iron axe  AT+12", /* [33] */
    "Battleax  AT+22", /* [34] */
    "", /* [35] */
    "Great axe  AT+27", /* [36] */
    "Ragnarok  AT+39", /* [37] */
    "Iron spear  AT+5", /* [38] */
    "Steel lance  AT+9", /* [39] */
    "Halberd  AT+13", /* [40] */
    "Dragon spear  AT+14", /* [41] */
    "Iron claws  AT+9", /* [42] */
    "Steel claws  AT+17", /* [43] */
    "Panzer claws  AT+20", /* [44] */
    "Death claws  AT+24", /* [45] */
    "Leather helm  DF+2", /* [46] */
    "Light helm  DF+3", /* [47] */
    "Iron helm  DF+7", /* [48] */
    "Steel mask  DF+12", /* [49] */
    "Grim helm  DF+15", /* [50] */
    "Dragon helm  DF+18", /* [51] */
    "Bandanna  DF+1  ", /* [52] */
    "Leather band  DF+2", /* [53] */
    "Iron cap  DF+5", /* [54] */
    "Steel band  DF+9", /* [55] */
    "Leather mask  DF+11", /* [56] */
    "Rune crown  DF+13", /* [57] */
    "Leather armor  DF+4", /* [58] */
    "Padded leather armor  \nDF+7", /* [59] */
    "Chain mail  DF+17", /* [60] */
    "Scale armor  DF+26", /* [61] */
    "Plate armor  AT+32", /* [62] */
    "Kevlar armor  DF+39", /* [63] */
    "Heavy cape  DF+2", /* [64] */
    "Wool robe  DF+4", /* [65] */
    "Master's robe  DF+10", /* [66] */
    "Mystic robe  DF+18", /* [67] */
    "Zen robe  DF+20", /* [68] */
    "Mojo robe  DF+26", /* [69] */
    "Holy key  Only Ash can \nuse it...", /* [70] */
    "Holy key  Only Ash can \nuse it...", /* [71] */
    "Holy key  Only Ash can \nuse it...", /* [72] */
    "Holy key  Only Ash can \nuse it...", /* [73] */
    "Holy key  Only Ash can \nuse it...", /* [74] */
    "Holy key  Only Ash can \nuse it...", /* [75] */
    "Magicalal and mysterious \ncrystal", /* [76] */
    "Magicalal and mysterious \ncrystal", /* [77] */
    "Magicalal and mysterious \ncrystal", /* [78] */
    "Magicalal and mysterious \ncrystal", /* [79] */
    "Magicalal and mysterious \ncrystal", /* [80] */
    "Necessary for Ash's \nadvancement", /* [81] */
    "Vandal helm", /* [82] */
    "Vandal armor", /* [83] */
    "Reforged Vandal Heart ", /* [84] */
    "Rare and expensive \nantique coins", /* [85] */
    "Precious metal used in \nalchemy", /* [86] */
    "Golden Axe  AT+0", /* [87] */
    "??????????", /* [88] */
    "??????????", /* [89] */
    "??????????", /* [90] */
    "??????????", /* [91] */
    "??????????", /* [92] */
    "??????????", /* [93] */
    "??????????", /* [94] */
    "??????????", /* [95] */
    "??????????", /* [96] */
    "Smelly green banana", /* [97] */
    "One of 3 collector's \ntreasures", /* [98] */
    "One of 3 collector's \ntreasures", /* [99] */
    "One of 3 collector's \ntreasures", /* [100] */
};
