/* GENERATED by platform/pc/tools/gen_string_table.py -- do not edit by hand. */
/* Runtime fixup for gStringTable (0x8010102c): the byte-exact text.c initializer
 * holds absolute PSX addresses that dangle on the PC port. We rewrite each entry
 * to the embedded string below at startup. See the generator header. */

extern unsigned char *gStringTable[100];

static const char *const s_pc_strings[100] = {
    "", /* [0] */
    "Ash", /* [1] */
    "Clint", /* [2] */
    "Diego", /* [3] */
    "Eleni", /* [4] */
    "Huxley", /* [5] */
    "Kira", /* [6] */
    "Grog", /* [7] */
    "Dolan", /* [8] */
    "Amon", /* [9] */
    "Sara", /* [10] */
    "Zohar", /* [11] */
    "Darius", /* [12] */
    "Depot", /* [13] */
    "Quit", /* [14] */
    "Champion", /* [15] */
    "Paragon", /* [16] */
    "Swordsman", /* [17] */
    "Duelist", /* [18] */
    "Guardsman", /* [19] */
    "Dragoon", /* [20] */
    "Bowman", /* [21] */
    "Sniper", /* [22] */
    "Hawknight", /* [23] */
    "Sky Lord", /* [24] */
    "Sorcerer", /* [25] */
    "Enchanter", /* [26] */
    "Monk", /* [27] */
    "Ninja", /* [28] */
    "Bishop", /* [29] */
    "Archbishop", /* [30] */
    "Vandalier", /* [31] */
    "  ", /* [32] */
    "Valley of Thieves", /* [33] */
    "Capital Shumeria", /* [34] */
    "Palace ruins", /* [35] */
    "Rhine Bridge", /* [36] */
    "Port City Minato", /* [37] */
    "Village of Yuzu", /* [38] */
    "Ygdra Canyon", /* [39] */
    "Loris Beach", /* [40] */
    "Castle ruins", /* [41] */
    "Plain of Sorrow", /* [42] */
    "Remote City", /* [43] */
    "Terasu Village", /* [44] */
    "Basil Gate", /* [45] */
    "Reed Highway", /* [46] */
    "Prison Fortress", /* [47] */
    "Khanos City", /* [48] */
    "Great Masai Forest", /* [49] */
    "Trade City Kerachi", /* [50] */
    "Railroad", /* [51] */
    "Fort Dain", /* [52] */
    "Wart Bay", /* [53] */
    "Pioneer town Sorbo", /* [54] */
    "Torog Mountains", /* [55] */
    "Frontier village", /* [56] */
    "Tsukue plains", /* [57] */
    "Smoking Bones Cave", /* [58] */
    "Orome Lake", /* [59] */
    "Glasgow City", /* [60] */
    "Fort Gareth", /* [61] */
    "Cobalt Beach", /* [62] */
    "Shop", /* [63] */
    "Dojo", /* [64] */
    "Tavern", /* [65] */
    "Leave Town", /* [66] */
    "Leave Village", /* [67] */
    "Sand Dunes of Sea", /* [68] */
    "Gadar Sea", /* [69] */
    "Security Force HQ", /* [70] */
    "Dover district", /* [71] */
    "Grog's house", /* [72] */
    "Carlo's mansion", /* [73] */
    "Old town warehouse", /* [74] */
    "Magic Train Station", /* [75] */
    "Guidance\nAdvance\nLeave Dojo", /* [76] */
    "Growth\n7 Powers\nHints\nLegend\nQuit", /* [77] */
    "Transform\nForget it", /* [78] */
    "Talk to", /* [79] */
    "Leave bar", /* [80] */
    "Bartender", /* [81] */
    "Young man", /* [82] */
    "Man", /* [83] */
    "Woman", /* [84] */
    "Old man", /* [85] */
    "Weird man", /* [86] */
    "Quit", /* [87] */
    0, /* [88] */
    0, /* [89] */
    0, /* [90] */
    0, /* [91] */
    0, /* [92] */
    0, /* [93] */
    0, /* [94] */
    0, /* [95] */
    0, /* [96] */
    0, /* [97] */
    0, /* [98] */
    0, /* [99] */
};

__attribute__((constructor))
static void PC_FixupStringTable(void) {
    int i;
    for (i = 0; i < 100; i++) {
        if (s_pc_strings[i]) {
            gStringTable[i] = (unsigned char *)s_pc_strings[i];
        }
    }
}
