/* GENERATED by platform/pc/tools/gen_spell_descriptions.py -- do not edit by hand. */
/* Reconstruction of gSpellDescriptions[72] (0x800ee9f8); the data-gen zero-fills
 * this pointer table, which blanked the battle spell/item info window. See the
 * generator header. Strings are verbatim from the byte-exact SLUS_004.47. */

char *gSpellDescriptions[72] = {
    " ", /* [0] */
    "Healing Magic  Rng:0  Fld:0  MP:2", /* [1] */
    "Attack Magic  Rng:1  Fld:0  MP:4", /* [2] */
    "Attack Magic  Rng:2  Fld:1  MP:8", /* [3] */
    "Healing Magic  Rng:2  Fld:0  MP:5", /* [4] */
    "Attack Magic  Rng:1  Fld:0  MP:10", /* [5] */
    "Attack Magic  Rng:4  Fld:0  MP:2", /* [6] */
    "Hold Magic  Rng:5  Fld:0  MP:2", /* [7] */
    "Attack Magic  Rng:4  Fld:1  MP:4", /* [8] */
    "Poison Magic  Rng:5  Fld:0  MP:3", /* [9] */
    "Attack Magic  Rng:0  Fld:7  MP:12", /* [10] */
    "Attack Magic  Rng:5  Fld:2  MP:6", /* [11] */
    "Poison Magic  Rng:5  Fld:2  MP:4", /* [12] */
    "Attack Magic  Rng:0  Fld:3  MP:7", /* [13] */
    "Attack Magic  Rng:6  Fld:0  MP:9", /* [14] */
    "Attack Magic  Rng:0  F:10  MP:14", /* [15] */
    "Healing Magic  Rng:4  Fld:0  MP:3", /* [16] */
    "Defense Up  Rng:4  Fld:0  MP:3", /* [17] */
    "Cure Status  Rng:4  Fld:0  MP:2", /* [18] */
    "Healing Magic  Rng:4  Fld:1  MP:4", /* [19] */
    "Attack Up  Rng:4  Fld:0  MP:3", /* [20] */
    "Attack Magic  Rng:4  Fld:0  MP:7", /* [21] */
    "Healing Magic  Rng:5  Fld:2  MP:5", /* [22] */
    "Restores MP  Rng:4  Fld:0  MP:10", /* [23] */
    "Attack Magic  Rng:5  Fld:1  MP:7", /* [24] */
    "Healing Magic  Rng:<  Fld:< MP:30", /* [25] */
    "Attack magic  Rng:0  Fld:1  MP:10", /* [26] */
    "Cure Status  Rng:0  Fld:1  MP:4", /* [27] */
    "Healing Magic  Rng:0  Fld:1  MP:6", /* [28] */
    "Protect Magic  Rng:4  F:0  MP:15", /* [29] */
    "Attack Magic  Rng:0  Fld:2  MP:12", /* [30] */
    "Healing Magic  Rng:0  F:2  MP:10", /* [31] */
    "DEF,AT Up  Rng:4  Fld:0  MP:15", /* [32] */
    "Healing Magic  Rng:0  Fld:0  MP:2", /* [33] */
    "Healing Magic  Rng:4  Fld:0  MP:3", /* [34] */
    "Healing Magic  Rng:5  Fld:1  MP:5", /* [35] */
    "Healing Magic  Rng:5  Fld:2  MP:8", /* [36] */
    "Healing Magic  Rng:0  Fld:1  MP:5", /* [37] */
    "Attack Magic  Rng:4  Fld:0  MP:3", /* [38] */
    "Attack Magic  Rng:6  Fld:0  MP:5", /* [39] */
    "Attack Magic  Rng:5  Fld:1  MP:5", /* [40] */
    "Attack Magic  Rng:5  Fld:2  MP:5", /* [41] */
    "Attack Magic  Rng:6  Fld:1  MP:8", /* [42] */
    "Attack Magic  Rng:4  Fld:2  MP:7", /* [43] */
    "Attack Magic  Rng:0  Fld:1  MP:5", /* [44] */
    "Attack Magic  Rng:<  Fld:<  MP:15", /* [45] */
    "Attack Magic  Rng:5  Fld:2  MP:15", /* [46] */
    "Attack Magic  Rng:6  Fld:0  MP:15", /* [47] */
    "Attack Magic  Rng:0  Fld:2  MP:20", /* [48] */
    "Restores HP  Rng:1  Fld:0", /* [49] */
    "Restores HP  Rng:1  Fld:0", /* [50] */
    "Cures Status  Rng:1  Fld:0", /* [51] */
    "Restores 4 MP  Rng:1  Fld:0", /* [52] */
    "Restores 10 MP  Rng:1  Fld:0", /* [53] */
    "Restores all HP, MP  Rng:1  Fld:0", /* [54] */
    "Restores party HP  Rng:<  Fld:<", /* [55] */
    "Attack item  Rng:3  Fld:1", /* [56] */
    "Attack item  Rng:0  Fld:2", /* [57] */
    "Attack item  Rng:5  Fld:3", /* [58] */
    "Attack item  Rng:0  Fld:8", /* [59] */
    "Attack Magic  Rng:8  Fld:0", /* [60] */
    "Attack Magic  Rng:8  Fld:0", /* [61] */
    "Attack Magic  Rng:9  Fld:0", /* [62] */
    "Hold Magic  Rng:5  Fld:0", /* [63] */
    "Poison Magic  Rng:5  Fld:2", /* [64] */
    "Restores HP  Rng:0  Fld:0", /* [65] */
    "Protect Magic  Rng:4  Fld:0", /* [66] */
    "Attack Magic  Rng:4  Fld:2", /* [67] */
    "Restores HP  Rng:0  Fld:1", /* [68] */
    "Attack item  Rng:5  Fld:2", /* [69] */
    "Attack item  Rng:0  Fld:1", /* [70] */
    "Attack item  Rng:6  Fld:1", /* [71] */
};
